config/routes.rb
Rails.application.routes.draw do
  get :story, to: 'home#view'
  get :altitude, to: 'home#view'
  get :wedding, to: 'home#view'
  get :registry, to: 'home#view'
  get :weekend, to: 'home#view'
  resources :invites do
    collection do
      get :import
      post :batch
      get :results
    end
  end
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :invite
end

app/models/invite.rb
class Invite < ApplicationRecord
  has_many :guests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def view
    if request.path == '/story'
      render 'story'
    elsif request.path == '/altitude'
      render 'altitude'
    elsif request.path == '/wedding'
      render 'wedding'
    elsif request.path == '/weekend'
      render 'weekend'
    elsif request.path == '/registry'
      render 'registry'
    end
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  require 'csv'
  def index
    if params[:email]
      invite = Invite.joins(:guests).find_by(guests: {email: params[:email].downcase})
      if invite
        redirect_to edit_invite_path(invite)
      else
        flash.now.alert = "#{params[:email]} is not registered to an invite.  Please try another one or contact us."
      end
    end
  end

  def edit
    @invite = Invite.find(params[:id])
  end

  def update
    @invite = Invite.find(params[:id])
    if params[:invite][:coming].to_i > @invite.invites
      flash.alert = "There is limited space for the reception and you are limited to #{@invite.invites} invites."
      return redirect_to edit_invite_path(@invite)
    end
    if @invite.update_attributes(invite_params)
      flash.notice = "You have successfully RSVP'd."
      redirect_to root_path
    else
      flash.alert = "There was an error saving your RSVP.  Please contact us."
      redirect_to edit_invite_path(@invite)
    end
  end

  def invite_params
    params.require(:invite).permit(:confirmed, :comments, :people, :coming)
  end

  def batch
    CSV.foreach(params[:csv].path, headers: true) do |row|
      Rails.logger.debug row.inspect
      guests = [Guest.new(email: row["email"], name: row["name"])]
      if row["spouse_email"]
      guests << Guest.new(email: row["spouse_email"], name: row["spouse_name"])
      end
      invite = Invite.create(invites: row["invites"], guests: guests)
    end
  end

  def results
    @coming = Invite.includes(:guests).where(confirmed: true)
    @declined = Invite.where(confirmed: false).includes(:guests)
    @undecided = Invite.where(confirmed: nil).includes(:guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/altitude.html.haml
%div{style: "margin: 20px 20px 0px 20px"}
  .card
    .card-section
      .h1 Preparing for High Altitude
      %p
        We will have our wedding in Mountain Village, which is 9,545’ in elevation. Here’s some tips on how to make sure your stay isn’t as affected by the altitude.  If you would like to read a more in depth article about it,
        %a{href: "https://www.uchealth.org/today/2017/12/15/altitude-sickness/", target: "_blank"}UCHealth
        has a good breakdown.
      %ul
        %li
          If you can, stay at a lower altitude for a night. Here are some places we recommend:
          %ol
            %li
              Ridgeway, CO - Not far from Montrose airport, there are some good economical options to stay the night, with a super cute downtown and a great place to grab
              %a{href: "http://www.provisionschef.com/"} food.
            %li Palisades, CO - Good halfway point from Denver to Telluride if you want to break up the drive. There are a bunch of wineries here, and the wine is nothing super notable. However, the peaches are famous, ripe this time of year, and totally worth getting.
            %li Denver, CO - Lisa and Alex live here, and are happy to recommend places to stay and things to do.
            %li Colorado Springs, CO - this is where Lisa grew up and her parents still live here.
            %li
              Boulder, CO - crunch on granola, watch some street performers on Pearl Street, and see if you can catch anyone saying anything found on this
              %a{href: "bloghttps://stayoutofmynamastespace.com/"} blog.
          %li Drink a lot of water, and take it easy on your first night in Telluride. If at any point you start to feel dizzy, sit down, have some water and get some form of salt into your system.
          %li Watch your alcohol! One beer may feel fine for you at sea level, but one beer at altitude may make you tipsy. Ease into the drinking.
  .card
    .card-section
      .h1 Preparing for a Drive
      %p While there is a small airport in Montrose, CO (less than 2 hours from Mountain Village), you may want to take a road trip from Denver's airport through the beautiful state of Colorado.
      %p We usually pass the time by downloading a few good podcasts. Here are a few we recommend:
      %ul
        %li
          %a{href: "https://www.dancarlin.com/hardcore-history-series/", target: "_blank"}Dan Carlin's Hardcore History
          %span - Dan Carlin is a journalist with a history problem. And a talking problem, with podcast episodes running anywhere from 2 hours to 4 hours in length. Take on his five part series on Ghengis Khan's rise and conquer of the steppe, or his six part series on the events leading up to and following the first World War. If you're the passenger, take a nap while Alex is driving and wake up to Dan Carlin talking about the exact same thing as when you fell asleep. Regardless of how you listen to it, be prepared to walk away sharing in Dan's infectious curiosity of past events.
        %li
          %a{href: "https://www.npr.org/podcasts/510324/rough-translation", target: "_blank"}NPR's Rough Translation
          %span - This series takes a conversation that's happening in the USA and watches it take place in a different country. Learn about how Brazil executes affirmative action by being more racist, or how a California court decision has given license to a nationalist movement in India, or how Jane Austen is making Pakistani women more feminist. Episodes are about 30 minutes in length.

app/views/home/index.html.haml
.hero-section
  .hero-section-text
    %h1 Welcome to Lisa and Alex's Wedding
    %h5 August 25, 2019
    %a{href: '/wedding'}
      .button.large Wedding Details

.grid-x.grid-padding-x{style: "margin: 30px 20px 0px 20px"}
  .cell.small-12.medium-4.text-center
    .card
      = image_tag 'mountain-lodge.jpg', class: "card-image"
      .card-section
        %h3 More About the Wedding
        %p
          August 25
          %sup
            th
          &nbsp;at The Mountain Lodge in Telluride, CO
        %a{href: '/wedding'}
          .button.hollow.large Learn More

  .cell.small-12.medium-4.text-center
    .card
      = image_tag 'christmas_partythumbnail.jpg', class: "card-image"
      .card-section
        %h3 Our Story
        %p Learn how we met.
        %a{href: '/story'}
          .button.hollow.large Learn More
  .cell.small-12.medium-4.text-center
    .card
      = image_tag 'telluride-valley.jpg', class: "card-image"
      .card-section
        %h3 Prepare for your trip
        %p Preparing for altitude and other things to do in Colorado.
        %a{href: '/altitude'}
          .button.hollow.large Learn More

app/views/home/registry.html.haml
%div{style: "margin: 20px 20px 0px 20px"}
  .card
    .card-section
      .h1 Registries
      %p We are registered for two registries, Zola and Amazon.  They are only online registries.
      .grid-x.grid-margin-x
        .cell.small-6.medium-6{style: 'text-align: center; padding-top: 15px;'}
          %a{href: "https://www.amazon.com/wedding/alex-orielly-lisa-vanarsdale-telluride-august-2019/registry/QTEE6DGRWPN5"}
            %img{src: "https://d1tntvpcrzvon2.cloudfront.net/vnassets/static/media/zola-logo-horizontal-black.34453bcb.svg", width: "200px"}
        .cell.small-6.medium-6{style: 'text-align: center'}
          %a{href: "https://www.zola.com/registry/alexandlisaaugust25"}
            %img{src: "https://tanyacostigan.files.wordpress.com/2016/02/amazon-registry-dc.png", width: "200px"}

app/views/home/story.html.haml
%div{style: "margin: 20px 20px 0px 20px"}
  .card
    .card-section
      .h1 Our Story
      %p We met when working for iTriage and both played for the company's recreational ultimate frisbee team. Alex had been playing since high school and Lisa was recruited because the coed team needed more women. Lisa is still terrible at frisbee to this day.
      %br
      %p We started becoming better friends and getting to know each other more. One day, Lisa asked Alex “how do you feel about the movie the Expendables?” And Alex mentioned how much he loved a good action movie. Lisa asked him out the next weekend.

      %br
      %p We started dating in October 2014 and currently enjoy their life in Denver. You can find them tending to their garden and beehives in the summer, and skiing or seeing a Broadway show in winter.
  .card
    .card-section
      %a{id: "pictures"}
      .h1 Pictures
    .card-section
      .grid-x.grid-margin-x
        .cell.medium-3
          = image_tag 'ChristmasParty_full.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "When It Began", "data-details" => "This gem is from the office Christmas party, at the place we met. We had been dating for less than two months when this was taken."
        .cell.medium-3
          = image_tag 'bees.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "Bees?!", "data-details" => "We have been keeping bees for three years now. Last summer, we harvested about 140 pounds of honey."
        .cell.medium-3
          = image_tag 'vienna.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "First Big Trip", "data-details" => "This was taken in Vienna, and was the start of our first big trip away together, where we travelled through Austria and Germany."
        .cell.medium-3
          = image_tag 'christmas.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "Christmas in Connecticut", "data-details" => "We have been spending Christmas with Alex's family in Connecticut together for the past three years. This picture was taken in 2017, at Christmas dinner in NYC."
    .card-section
      .grid-x.grid-margin-x
        .cell.medium-3
          = image_tag 'belize.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "Better Belize It!", "data-details" => "We took a trip to Belize together with some friends in 2018. Here's us exploring a Mayan ruin."
        .cell.medium-3
          = image_tag 'shipleys.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "Donuts", "data-details" => "Okay, so Lisa loves donuts. So, she picked this picture of us in Austin, at her favorite donut shop."
        .cell.medium-3
          = image_tag 'japan.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "Japan", "data-details" => "We got some stunning photos of the two of us in Japan to celebrate our engagement. Here's us on our best behavior."
        .cell.medium-3
          = image_tag 'peoplesjapan.jpg', class: 'gallery cursor', "data-open" => "modal", "data-title" => "Also Japan!", "data-details" => "And here's us, again in Japan, how we typically took pictures. Seen with the People's Eyebrow."



#modal.reveal.large.text-center{"data-reveal" => ""}
  .grid-x
    .cell.medium-3.text-left
      %h3#reveal-title
      %p#reveal-details
    .cell.medium-9
      %img#reveal-image
  %button.close-button{"aria-label" => "Close modal", "data-close" => "", :type => "button"}
    %span{"aria-hidden" => "true"} &#215;

:javascript
  $(document).on('turbolinks:load', function(){
    $('.gallery').on('click', function(){
      $('#reveal-image').attr('src', $(this).attr("src"));
      $('#reveal-title').text($(this).attr("data-title"));
      $('#reveal-details').text($(this).attr("data-details"));
    });
  });

app/views/home/wedding.html.haml
%div{style: "margin: 20px 20px 0px 20px"}
  .card
    .card-section
      .h1 Wedding Details
      %p
        We are getting married on August 25th, 2019 at 5:30, at the
        %a{href: "https://www.mountainlodgetelluride.com/suites"}Mountain Lodge
        near Telluride, CO.
      %p
        %div The dress code will be to look nice, but not too fancy.
        %div Women: No jeans, no ballgowns. No colors are off limits - the bride will be in red.
        %div Men: Only punks go to a wedding without a jacket.
      .h4 Wedding Schedule
      %div 10am-3pm Brides Getting Ready(Madeline Salon in Mountain Village)
      %div 1-3pm Grooms Getting Ready(Mountain Lodge in Telluride)
      %div 3-5pm First Look and wedding party pictures
      %div
        %b 5:30-6pm Ceremony (on pool deck)
      %div 6-7pm Cocktail hour & family pictures
      %div 7-8pm Dinner
      %div 8-8:15pm Toasts
      %div 8:15-8:45pm Cutting cake
      %div 9-11pm Dance and have fun
      %br
      .h4 Accommodations
      %p
        We have a block of rooms reserved with the Mountain Lodge - please contact Sam Barnes at
        = mail_to "sbarnes@mountainlodgetelluride.com", "sbarnes@mountainlodgetelluride.com"
        or book online with the code
        %em“VANARSDALE”.
        If you are planning to book a cabin (3-6 bedrooms), it's encouraged that you book as early as possible due to the limited availability. However, there are many 1-2 bedroom options available. Reach out to Sam with any questions.

app/views/home/weekend.html.haml
%div{style: "margin: 20px 20px 0px 20px"}
  .card
    .card-section
      .h1 Wedding Weekend
      %p Whenever you are able to join us in Telluride, there will be something going on. Feel free to join in on as much or as little as you want:

      .h5{style: "margin-bottom: 0px"} Friday
      %div 9am: Breakfast at the VanArsdale cabin
      %div
        7pm: Meet for drinks at the
        = link_to "Last Dollar Saloon", "https://lastdollarsaloon.com"
        in Telluride
      %br
      .h5{style: "margin-bottom: 0px"} Saturday
      %div 9am: Breakfast at the VanArsdale cabin
      %div
        10am: Carpool up to the
        = link_to "Alta Lakes", "https://www.gjhikes.com/2018/08/alta-lakes.html"
        for some hiking and picnicking. The drive is about 30 minutes from the hotel and 4WD is recommended.
      %br

      .h5{style: "margin-bottom: 0px"} Sunday
      %div 9am: Breakfast at the VanArsdale cabin - (groom not invited)
      %div 5:30pm: Wedding
      %br

      .h5{style: "margin-bottom: 0px"} Monday
      %div 9am: Breakfast at the VanArsdale cabin

app/views/invites/edit.html.haml
.grid-x.grid-margin-x{style: "margin: 20px 20px 0px 20px"}
  .cell.small-12.medium-8.medium-offset-2
    .card
      .card-section
        %h3 Please fill out the fields below to RSVP.
        %h4 Notes about the RSVP
        %ul
          %li
            While little ones are welcome in Telluride, we will be having a child-free wedding and reception on Sunday. Reach out to us if you have any concerns or need help finding child care.
          %li
            If you were expecting more members of your party than what is listed, please contact us directly before RSVPing. Space is limited in the venue, and our wedding is not clown-car themed.
        .grid-x.grid-margin-x
          .cell
            = form_for @invite do |f|
              = f.label :confirmed, "Will you be attending?"
              = f.radio_button :confirmed, :true
              = f.label :yes
              = f.radio_button :confirmed, :false
              = f.label :no
              #hidden{style: 'display: none'}
                = f.label :invites, "You have <b>#{@invite.invites}</b> total invites.  How many are coming?".html_safe
                = f.text_field :coming
                = f.label :people, "Who is coming to the wedding? This is helpful so we can create place cards."
                = f.text_area :people, rows: 4
                = f.label :comments, "Please post any additional needs or comments here."
                = f.text_area :comments, rows: 6
              %div
                = f.submit :Submit, class: "button large"
:javascript
  $('#invite_confirmed_true').on('click', function(){
    $('#hidden').css('display', 'block');
  });

  $('#invite_confirmed_false').on('click', function(){
    $('#hidden').css('display', 'none');
  });

app/views/invites/import.html.haml
= form_tag batch_invites_path, multipart: true do
  = file_field_tag :csv
  = submit_tag "Submit", class: "button large"

app/views/invites/index.html.haml
.grid-x.grid-margin-x{style: "margin: 20px 20px 0px 20px"}
  .cell.small-12.medium-8.medium-offset-2
    .card
      .card-section
        %h3 Look up your invitation by email
        %p
          It will be the same email where we sent the save the date.
        .grid-x.grid-margin-x
          .cell.small-6.medium-6
            = form_tag :invites, method: :get do
              = text_field_tag :email, nil, placeholder: "Email Address"
              = submit_tag "Submit", class: "button large"

app/views/invites/results.html.haml
.grid-x.grid-margin-x{style: "margin: 20px 20px 0px 20px"}
  .cell.small-12.medium-8.medium-offset-2
    .card
      .card-section
        %h3
          .grid-x.grid-margin-x
            .cell.small-10
              Coming
            .cell.small-2
              = @coming.sum{|invite| invite.coming.to_i }
        - @coming.each do |invite|
          .grid-x.grid-margin-x{style: "border-top: 1px solid #e2e2e2"}
            .cell.small-3
              = invite.guests.first.name
            .cell.small-1
              = invite.coming
            .cell.small-3
              = invite.people&.gsub("\r\n", '<br />')&.gsub("\n", '<br />')&.html_safe
            .cell.small-5
              = invite.comments
    .card
      .card-section
        %h3
          .grid-x.grid-margin-x
            .cell.small-10
              Declined
            .cell.small-2
              = @declined.sum{|invite| invite.invites}
        .grid-x.grid-margin-x
          - @declined.each do |invite|
            .cell.small-5
              = invite.guests.first.name
            .cell.small-5
              = invite.guests.first.email
            .cell.small-2
              = invite.invites
    .card
      .card-section
        %h3
          .grid-x.grid-margin-x
            .cell.small-10
              Undecided
            .cell.small-2
              = @undecided.sum{|invite| invite.invites}
        .grid-x.grid-margin-x
          - @undecided.each do |invite|
            .cell.small-5
              = invite.guests.first.name
            .cell.small-5
              = invite.guests.first.email
            .cell.small-2
              = invite.invites

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "VanRielly Wedding"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body{style: "background-color: #cfd9ea"}
    %nav.top-bar.topbar-responsive
      .top-bar-title
        %span{"data-hide-for" => "medium", "data-responsive-toggle" => "topbar-responsive"}
          %button.menu-icon.hide-for-medium{"data-toggle" => "", :type => "button"}
        %a.topbar-responsive-logo{:href => "/"}
          %strong O'Rielly & VanArsdale Wedding
      #topbar-responsive.topbar-responsive-links
        .top-bar-right
          %ul.menu.simple.vertical.medium-horizontal
            %li
              %a{:href => "/story"} Our Story
            %li
              %a{:href => "/wedding"} Wedding Details
            %li
              %a{:href => "/weekend"} Weekend Schedule
            %li
              %a{:href => "/altitude"} Travel Tips
            %li
              %a{:href => "/registry"} Registry
    - flashes = {notice: 'success', alert: 'alert'}
    - flashes.each do |key, value|
      - if flash[key]
        .callout{class: value, data: { alert: '' } }
          = flash[key]
    = yield